# Numpy

In [1]:
import numpy as np

In [3]:
l = [1,2,3,4,5]
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
type(l)

list

In [9]:
arr.shape

(5,)

In [10]:
arr2 = np.arange(1,5)

In [11]:
arr2

array([1, 2, 3, 4])

In [12]:
arr2.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [13]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
arr.shape

(3, 5)

In [16]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

# index

In [17]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [18]:
arr[1]

array([2, 3, 4, 5, 6])

In [19]:
arr[1][1]

3

In [20]:
arr[1,1]

3

In [23]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [26]:
arr = np.arange(0,10,step=2)

In [27]:
arr

array([0, 2, 4, 6, 8])

In [28]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [32]:
val=2
arr
arr<4

array([ True,  True, False, False, False])

In [33]:
arr

array([0, 2, 4, 6, 8])

In [34]:
arr/2

array([0., 1., 2., 3., 4.])

In [36]:
arr[arr<6]

array([0, 2, 4])

In [37]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.random.rand(4,5)

array([[0.40883802, 0.8428423 , 0.30025527, 0.96329961, 0.88030204],
       [0.94866399, 0.15840193, 0.141325  , 0.40969132, 0.8018841 ],
       [0.02177605, 0.74288701, 0.31202554, 0.89262595, 0.39793568],
       [0.70253941, 0.76785549, 0.24341761, 0.72070981, 0.91430094]])

In [47]:
arr_ex=np.random.randn(4,4)

In [48]:
arr_ex

array([[-1.37752357, -0.06110866,  0.75910331,  1.5367265 ],
       [-1.00721226, -1.04405859,  0.55158438, -0.19020459],
       [-1.33774981,  1.21368102,  0.15557926, -0.53201852],
       [ 0.5403469 ,  1.23666001, -1.56667784, -0.94708914]])